const categories = [
  { value: "blues", label: "Blues" },
  { value: "rock", label: "Rock" },
  { value: "country", label: "Country" },
  { value: "dance", label: "Dance" },
  { value: "disco", label: "Disco" },
  { value: "punk", label: "Funk" },
  { value: "grunge", label: "Grunge" },
  { value: "hiphop", label: "Hip-Hop" },
  { value: "jazz", label: "Jazz" },
  { value: "metal", label: "Metal" },
  { value: "oldies", label: "Oldies" },
  { value: "pop", label: "Pop" },
  { value: "r&b", label: "R&B" },
  { value: "rap", label: "Rap" },
  { value: "reggae", label: "Reggae" },
  { value: "techno", label: "Techno" },
  { value: "industrial", label: "Industrial" },
  { value: "alternative", label: "Alternative" },
  { value: "ska", label: "Ska" },
  { value: "deathmetal", label: "Death Metal" },
  { value: "house", label: "House" },
  { value: "game", label: "Game" },
  { value: "gospel", label: "Gospel" },
  { value: "soul", label: "Soul" },
  { value: "punk", label: "Punk" },
  { value: "gothic", label: "Gothic" },
  { value: "electronic", label: "Electronic" },
  { value: "lofi", label: "Lo-Fi" },
  { value: "musical", label: "Musical" },
  { value: "hardrock", label: "Hard Rock" },
  { value: "folk", label: "Folk" },
  { value: "swing", label: "Swing" },
  { value: "latin", label: "Latin" },
  { value: "progressiverock", label: "Progressive Rock" },
  { value: "acoustic", label: "Acoustic" },
  { value: "humour", label: "Humour" },
  { value: "opera", label: "Opera" },
  { value: "tango", label: "Tango" },
  { value: "samba", label: "Samba" },
  { value: "folklore", label: "Folklore" },
  { value: "freestyle", label: "Freestyle" },
  { value: "acapella", label: "Acapella" },
  { value: "reggaeton", label: "Reggaeton" },
];

module.exports = categories;
